### ISSUE TITLE
missing info/files?

### ISSUE THREAD

**Issue by cats-suzanne** [IGBIllinois/SLURM_generator#1] opened 2024-08-26 17:06 UTC
Hi,

Trying to get this working on my end, and I am guessing there are a number of prerequisite system packages needed that aren't listed (particularly java?) in the readme. Also, the source code itself references a number of scripts in a subdirectory named vendors/, which does not exist in the files pulled from the git repository. My site loads as configured according to the instructions, and successfully reads the queue data in my configure.json file, but the dropdown menus don't work and no script is generated, so clearly I am missing something. Thanks (-:

**Comment by dslater82** [comment] 2024-08-27 13:10
Hi,

Looks like in our instructions, we didn't have run "composer install".  This will install the javascript files, bootstrap, jquery, etc.  Give that a try.  I'm actually moving this to a new server in a near future so I'm sure I'll run into the same issues that you are and I'll make sure to get everything updated if I am missing something.

**Comment by cats-suzanne** [comment] 2024-08-27 13:46
Ah! Yes, that did the trick. Had to install a few other system packages. If you want my step-by-step for Ubuntu 22.04, let me know. Thanks so much (-:

**Comment by dslater82** [comment] 2024-08-27 14:29
I added composer install to the installation and I can confirm it works also.  What other packages did you need to install.  I'm on Rocky Linux.  I am guessing just some php packages which I can add to the composer file.

**Comment by cats-suzanne** [comment] 2024-08-27 14:36
php-curl and composer 

Also, I had to run the composer install as a non-root user, so that required tinkering just a bit with the permissions on the folder, but otherwise pretty simple.

**Comment by dslater82** [comment] 2024-08-27 14:51
Thanks.  I added ext-curl to composer file and a link to installing composer in the README.md.  The non-root user/permissions is kindof beyond the realm of the program itself.  I can't account for every setup out there.

Glad you are using it!

**Closed as completed by dslater82** 2024-08-27 14:51 UTC
